export const SEARCH_SONGS='SEARCH_SONGS'; //ACCION DE BUSQUEDA AL ESCRIBIR EN EL INPUT
export const FETCH_SONGS='FETCH_SONGS';//ACCION DE BUSCAR TEXTO DEL INPUT CON TITULOS DE LAS CANCIONES EL LOS DATOS DE LA API
export const FETCH_SONG='FETCH_SONG'//BUSCAR INFORMACION DE LA CANCION SELECIONADA
export const FETCH_INFO='FETCH_INFO'
export const LOADING='LOADING'